spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    import: application-secret.yml
