spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    import: application-secret.yml
