spring:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    import: application-secret.yml

  logging:
    level:
      com:
        amazonaws:
          util:
            EC2MetadataUtils: error
